services:
  - type: web
    name: ecovigia-api-ssvv
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: postgresql://ecovigia_3kum_user:8ypp4SgZVfRff0ZwqhLXftBg3NRoUgZT@dpg-d0mfk3be5dus738g0dg0-a/ecovigia_3kum
      - key: CLIENT_URL
        value: https://ecovigia-site-aj00.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: dpjf1w7bw
      - key: CLOUDINARY_API_KEY
        value: 168314576313623
      - key: CLOUDINARY_API_SECRET
        value: EkCHl_OfyD9UphRZmAJpDD_SXb8
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .

  - type: web
    name: ecovigia-site-aj00
    runtime: static
    buildCommand: ""
    staticPublishPath: client
    autoDeploy: true

# banco gerenciado PostgreSQL
databases:
  - name: ecovigia_3kum
    plan: free
    ipAllowList: [] 