services:
  - type: web
    name: ecovigia-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: postgresql://ecovigia_user:RzCDm1TzkVEleFiOY7cSEqjCD3vlwAbo@dpg-d0mf4ojuibrs73elms0g-a.oregon-postgres.render.com/ecovigia
      - key: CLIENT_URL
        value: https://ecovigia-site.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: dpjf1w7bw
      - key: CLOUDINARY_API_KEY
        value: 168314576313623
      - key: CLOUDINARY_API_SECRET
        value: EkCHl_OfyD9UphRZmAJpDD_SXb8
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .

  - type: web
    name: ecovigia-site
    runtime: static
    buildCommand: ""
    staticPublishPath: client
    autoDeploy: true

# banco gerenciado PostgreSQL
databases:
  - name: ecovigia
    plan: free
    ipAllowList: [] 