services:
  - type: web
    name: ecovigia-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false 
      - key: CLIENT_URL
        value: https://ecovigia-site.onrender.com
    autoDeploy: true
    rootDir: .

  - type: web
    name: ecovigia-site
    runtime: static
    buildCommand: ""
    staticPublishPath: client
    autoDeploy: true

# banco gerenciado MySQL
databases:
  - name: ecovigia-db
    plan: free
    ipAllowList: [] 